### ISSUE TITLE
NO CS DEGREE & DEVELOPER INTERVIEWS

### ISSUE THREAD

**Issue by jidemusty** [ireade/ama#29]
Hi, Ire

My question is about you not having a CS degree, did this in any way make you come short when applying for jobs or during technical or non-technical interviews, did you have to catch up on computer science stuffs like data structures and algorithms to be able to pass these technical interviews.

kind regards.

**Comment by ireade** [comment]
Hi @jidemusty !

There were some technical interviews that I struggled with because I never learned about stuff like data structures and algorithms. But in those cases, the jobs were not a good fit for me anyway. Since my focus is on frontend development, I don't think that a CS degree would have helped in any way. It may be more important if you are looking for a different type of programming job.
