### ISSUE TITLE
Why don't you use frameworks?

### ISSUE THREAD

**Issue by THEozmic** [ireade/ama#5]

**Comment by ireade** [comment]
I don't use HTML/CSS frameworks like Bootstrap, because I personally find them frustrating to work with. I find that I write much better, semantic, accessible markup and CSS without them, and am much faster.

Those frameworks can be useful when you're starting out, but they should never be a crutch. Once you start becoming a mid-level front-end developer, you need to be able to work without them. That doesn't mean you can't use them, just that you should understand what they are doing and not be completely dependent on them.

**Comment by oluwaseunmusa** [comment]
Ireade I totally agree with you.  When you understand the functionality of this framework then should create yours.
