### ISSUE TITLE
How did you got the "Google Expert in Web Tech" title?

### ISSUE THREAD

**Issue by diogokobbi** [ireade/ama#8]
Could you tell us more about your learning path?

**Comment by ireade** [comment]
Hi @diogokobbi !

I got the title by being a part of [Google's Experts Program](https://developers.google.com/experts/). To become an Expert, you have to be nominated by either a Googler or another Expert, then undergo a series of interviews (technical and otherwise). You can learn more about becoming an expert [here](https://developers.google.com/experts/become-an-expert)
